import Config

# Inject the Umami analytics snippet on the public site. Off in
# dev/test (so we don't pollute the dashboard with our own clicks).
config :super_barato, :analytics_enabled, true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :super_barato, SuperBaratoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :super_barato, SuperBaratoWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Prod logging: keep it at :info. Format includes chain + role so log
# aggregators can filter and group pipeline lines per supermarket.
# Format matches config.exs default (timestamp + metadata + message)
# unless the deploy target replaces it (e.g. with JSON structured logs).
config :logger, level: :info

config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :chain, :role]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
