defmodule SuperBarato.Repo.Migrations.ProductsThumbnailKey do
  use Ecto.Migration

  # R2 object key for the product's pre-rendered thumbnail
  # (~400px max edge, WebP). Generated by SuperBarato.Thumbnails on
  # crawl ingest or via `mix thumbnails.backfill`. Nullable while
  # backfill is in progress; the home cards fall back to the raw
  # chain CDN `image_url` when the key isn't set yet.
  def change do
    alter table(:products) do
      add :thumbnail_key, :string
    end
  end
end
